### ISSUE TITLE
Comments in INI file generate error

### ISSUE THREAD

**Issue by jkour** [WladiD/Localization#1]
Hi,
the comments in the local INI files (#) break the code. 

In the demo, when the code reads the [Strings] section, it does not stop at the '# You can choose any numeric start id, but it should not collide with the id range...' and tries to convert it to integer.

This generates an error.

Thanks

**Comment by WladiD** [comment]
Hi John,

sadly I was not notified about this issue or I overlooked it.

This bug is already fixed, after I want to use it in [WinDomina](https://github.com/WladiD/WinDomina).

Best regards!
